---
name: terraform apply
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: prod
    env:
      ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
      ARM_USE_AZUREAD: true
      ARM_USE_OIDC: true
      TF_IN_AUTOMATION: 1
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="container_name=${{ vars.BACKEND_STORAGE_CONTAINER }}" \
            -backend-config="key=${{ vars.BACKEND_KEY }}" \
            -backend-config="resource_group_name=${{ vars.BACKEND_RESOURCE_GROUP }}" \
            -backend-config="snapshot=true" \
            -backend-config="storage_account_name=${{ vars.BACKEND_STORAGE_ACCOUNT }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve
