---
name: token blurbs
on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  token:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: token
        timeout-minutes: 10
        with:
          debug: true
          script: |
            const token = process.env['ACTIONS_RUNTIME_TOKEN']
            const runtimeUrl = process.env['ACTIONS_ID_TOKEN_REQUEST_URL']
            core.setOutput('TOKEN', token.trim())
            core.setOutput('IDTOKENURL', runtimeUrl.trim())
      - run: |
          IDTOKEN=$(curl -H "Authorization: bearer  ${{steps.token.outputs.TOKEN}}" ${{steps.token.outputs.IDTOKENURL}}?audience=api%3A%2F%2FAzureADTokenExchange  -H "Accept: application/json" -H "Content-Type: application/x-www-form-urlencoded" | jq -r '.value')
          echo $IDTOKEN | base64
