---
name: token blurbs
on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  token:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo b64
          echo "$ACTIONS_ID_TOKEN_REQUEST_TOKEN" | base64
